apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/rancher/local-path-provisioner
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./deploy
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner
  patches:
    - target:
        group: ""
        version: v1
        kind: Namespace
      patch: |-
        - op: add
          path: /metadata/labels
          value:
            pod-security.kubernetes.io/enforce: privileged
