apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/nfs-subdir-external-provisioner/homelab
  sourceRef:
    kind: GitRepository
    name: flux-system
