apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/podinfo/overlays/homelab
  sourceRef:
    kind: GitRepository
    name: flux-system
