apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: 1.15.5
  releaseName: cilium
  values:
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    ipam:
      mode: kubernetes
    kubeProxyReplacement: strict
    encryption:
      enabled: true
      type: wireguard
      # strictMode:
      #   enabled: true
    hubble:
      relay:
        enabled: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
      tls:
        enabled: true
        # auto:
        #   method: certmanager
        #   certManagerIssuerRef:
        #     group: cert-manager.io
        #     kind: ClusterIssuer
        #     name: hubble-issuer
      metrics:
        enabled: [dns:query;ignoreAAAA, drop, tcp, flow, icmp, http]
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
    ingressController:
      enabled: true
      default: true
      # service:
      #   type: ClusterIP
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
  valuesFrom:
    - kind: Secret
      name: k8s-host
      valuesKey: host
      targetPath: k8sServiceHost
    - kind: Secret
      name: k8s-host
      valuesKey: port
      targetPath: k8sServicePort
  targetNamespace: kube-system
  interval: 1m0s
