apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tetragon
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tetragon
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: 0.10.0
  targetNamespace: kube-system
  interval: 1m0s