apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
      version: 0.26.0
  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
  targetNamespace: cnpg-system
  install:
    createNamespace: true
    crds: CreateReplace
  interval: 1m0s
