apiVersion: v1
data:
    config.json: ENC[AES256_GCM,data:DghUuVvi48fhXMkCWTEq/12iufwf5otD0lzmX0aEqPWrR7SxMNn/ZZiXw9n/uKW5umo2qIueE9Emz6uzfociePuFY1J1kxrwoa2L0FqCpW8ynxObT0kpFdA0wfrUeAeENq+AcM7ytYXTkxGBMWbjOLCEMD2A9KGW4je9MmrdLPaBG2c7Enf/mYbqZSNTXQ9UjwIAJ3cDPCamKhT3PYd8CXfWCTdoCcpvpuCqdTbKCEslU7xo1YoROw9wCUm9BhxEiQgEnpIUkS2/P4NPzhfBBp0H0/mwCClf/g5cnbs7o7623UTVdN60shXt8LE8maJJFiaMOXDssQAnP5TD0WX9TvpiJmj6QtibHg/EBP/SInRBazmit4AqphuTkUwow21L8mfRZJFv63L1YFR/h3MjbgtxUPs/+DcVfKNnPqOAVZpEuf8Soy//Aw1rTI0t95aC,iv:QfjTSTtZI1xDFHEWv9tVr44+WmsXhwYlGXrF6UsJKXM=,tag:t2ksbenSC1DZ0ECFW1vdug==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-regcred
    namespace: tekton-builds
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-20T01:01:40Z"
    mac: ENC[AES256_GCM,data:L6CPwmiJrKMa69dgx2/OvHL0+PzVCsx1Kxb6vN7pxho4SKz3UH4iOV6N0iTp9VtQAneFN5+wBH5EfBkKB91djqGLu10jCtCmgVhVTAHH8piSpfasZV3dGmSHxltil7JQnh5i49HXr8+DSpNsDkco9r9NTaLFtknC47KGPvnl4R4=,iv:6P8ychtreUECa4x0fGu1rXVbwjm8eVTcAhC4z8Ge8f4=,tag:BvaRassneClwGpcwNmwOwA==,type:str]
    pgp:
        - created_at: "2024-03-20T01:01:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3RMxBeN8HBhAQ/+Mlc9Yil+Rx5uzR1Qpw+kk6rsl8tl9l2DFPXSK4RnJQBb
            lXWizyySp7RIDCg+Sjhlu2G6uqtihIgjBoS8Z47OQ8UQ4vsE/VRC0OOJvUfYDWhY
            cmt205WaGrAbSvJr7TXA3Rgv6ChQMZR/dZiCeAcmgYERsHIsFYac6h4iRPtEwNBy
            SKx6qA83NK8Vw51Fdmn9OyDWdcINStbbjn1wr0DkipT2FCUP2jFkmariQjDCZeHj
            6woBKsSheVt9a9rnvIBc6254b6uPbkM5K+O0jZxbKmOjYUyw2c9gf3LrafvZ8O3d
            fL5AJ+SnRdLy1hWSSsZza4oe3GNI66rt+3ux3UvdH2ExYWPzgBpScjDZU+Qa9S/a
            m/DqWeF9Zmfd9/U9UJffvW4ZrRHC9WZVym7XwiTmKxzeGhDiRQiUDLx8yWs6U4vU
            TmsE7df9uYKGR/4DXTZBbp05zp4/vCYtRz9iq9r4fxMvHqXRGsbCVpJfDOBfAHlV
            F4uFqo3hI+yug5oe2D51xfHmrcg+NaXgREuWvm1F4fkaLUqSAIg0owinwrOktBvF
            i2eeJdd4qR3KmrgWIcCNFg/82LqyNxh2yvLSVbAGxMkq2+kytYSycx5aQ7JJSvt9
            +C9/ldDkJcaQRPDex3+5KolhILXrEf/AEdoCiGIXGJMWHHO2TQHs/Y/Kgf64j5jU
            aAEJAhCDfCQzJ2Ymyj8Plrxvb1r7ajop9LMUIbiow/0CNTeU885NHlkIoo251zn2
            DC1lg+muTIeXOBi9UYhDgaNQ0IacPgb7qhP+5C8bwmkzTDvsevU9OPxW4WgpMdkE
            xKhfCJLgzZMG
            =Zl2E
            -----END PGP MESSAGE-----
          fp: 37789BA069FF4ED2CC9090EEA05A04C2254C3CF1
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
