apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.linkerd.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: flux-system
spec:
  chart:
    spec:
      chart: linkerd-crds
      sourceRef:
        kind: HelmRepository
        name: linkerd
      version: 1.6.1
  targetNamespace: linkerd
  interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: flux-system
spec:
  chart:
    spec:
      chart: linkerd-control-plane
      sourceRef:
        kind: HelmRepository
        name: linkerd
      version: 1.12.5
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: tls.crt
      targetPath: identityTrustAnchorsPEM
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
  targetNamespace: linkerd
  interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
      version: 30.8.5
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: linkerd-jaeger
      sourceRef:
        kind: HelmRepository
        name: linkerd
      version: 30.8.5