apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:+6RHVLx+QCE1e/Axm2ZXJMLrvkqmpdjSy5Z5067y69FTFTEHSGjOMFOTyHYVbHxMk9pqHmtAqCqCCz28mzE3NAoCqefwPsd9/klrEo/xMi2HdECysq3W8EbJvUvV,iv:fylMlEpmmtRLpcgQE8ap0npw48AwwP7A4EGTBS4YP50=,tag:9cQU0clxMQUt2gbPw8CKSA==,type:str]
    #ENC[AES256_GCM,data:/pQyyPk/K5YqJauSb+LvRz8BNUT0b7765R1pXm3mDay/gj23oomT2563KleZE6Isnrp6FyGYHbOWqdOhtooF8bG3GYhUfaNmwDVJwReBM+m+qW8fMOYzJQ+9Nayzbpo=,iv:O93crsF7S4HBSK1w2GiT35YRpZzlBx3htUAtvBnLsZg=,tag:LjR9xbAOViMREBRAe687yA==,type:comment]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:U2rmOak=,iv:KpUzoXg0Z6BNOD1OFeMRoxmJANDbAosLZ5vYiEqdPsU=,tag:YMTyXEqRVQi/5d2D8dA05A==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:aTDbTdJ5ImuxHcFsDwyzPVcQuWxJSWcqoIdd6km31wnq,iv:kn648nVDMahmcfPmPZ4/lGxFd/42xWkjLbIa732Jy0A=,tag:a5P2cPPgOz3S0tTnl5eqQQ==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:aWVgOrjMFf0E2CqYOcyhIuEhP7PsLajfe1PZuSabMSocRw==,iv:v6cRHBP2d1VgY9wQxi1YgzHHylwjvo2OSXu1zpvE0k8=,tag:6A3Qn6O0wewwhFWOqcAT4Q==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:nuRBeUZ8,iv:7ZEs2jhYhlD/ihs3vdoQTtZhptbMpG/yIQR4Jo5Bvo0=,tag:vykwwylMWDKKm0moRRBvtg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:n/i1ApCwkND8OJcifLQrGtLx6ADkycYnYF2Jj0lQRG1d0k4tFTb5Cu/j2bRGPFCggYSxSbgxt9WfLBqcodSKiGYYeEDWmLa6cX7DP9Y/DRaHK3QMgZtB+hkZ4K49,iv:EgdVCr5iSDbfbChuGswbZzIXHu4mznXnD4Vp4X46XL8=,tag:w87tGh6kbtegxURdGs2G0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-07T15:55:12Z"
    mac: ENC[AES256_GCM,data:dX1QlAep089vL99Uos34iD9wwYTZdjbiPLcfwtc+L6XdC3WfH0VpXj74RUNQ4p6DsZePpqQY4d89SGCxHOfrqNsajD7FxQESLSZmP56BYlGWM937s0/Zk4i4FsCt40gizXIdRyt6IoRxStYdHhmAH8GDixCY49TUS8YzcrXlkwU=,iv:lEfmOHEKDoQ/0sipgvRVqRw7GyB0leoJaKMDcyo1E9A=,tag:Elxsly1NyliBRGI4saOJKA==,type:str]
    pgp:
        - created_at: "2024-12-07T15:55:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0Q4ZLDeaJuFARAAmKJwQ6pm6ZdwwB1lSTWUjZm2xVOZBbkDCQVOtN0UsDo9
            Tiu4jsn9PxjOUbAF+zVTaNKIPr02QPum0SDIwhoty4IB+x7KNolSbso0T8j4SwnN
            V6Pz1i4GapJ8Ba2ngdaoH9+jawMOR8X/rfsZSjYWPEg5mUSY+yOiNhX7p5DFtGdC
            EPspuqnzWtAibCscydqDrLRjzSwPlpdfUl1TW7o8WFUMJGZFNtMns8z3s+/wjq2a
            NOuzTxhGdLzk+1+/bB+Cbg3rD4/nvmIXuuQL0J3nbG4uAtMRO/4fTaaaGqBGNbzq
            8WzvV169FSwxxZODGBeax3zFu6GFf8wAbghR+MIeVrViqE4gYCTVh0mdZqpadbzC
            7uOlKEUH7o//LZNqkIKyA32Y7cMFZGnmH5kTOOVQWJso8UJJScJUdGPYHHoavxzw
            EYdrKYuzRjfPagyhxbGXQQINm1yuF+BC0m9UhSppT45gHNyD0cGdd5XjeChca/e5
            C5JENlkmak7x9fA7dIxMsrKoCVsRaOA3rKygDvTU+PwBYhLUlPPd/OLsrm11EpbS
            QX5euLJtw08N8rd3tiQ2qvBjqmPGmJg+IQMMRA5Ai/hiAdN2dum0wI+0/r1KVXtf
            +KNwqXQ4axnXFj/DJzhmXyq8hsvWB9Gpy0QDHqqbYPWNWIOQobl6qrR/JRhTHQLS
            XgFthUqnu6llWAtQdsC3q5qzhta1928dsAttTPfTS73JWFCnaeKDCFPVmqkiDlKH
            PRFZzBLRxXV8pIL+D0qgOhHqTXCrfsb8EiG9idgyYbnMJs8NvElkJQMw7smG0Rw=
            =DRNg
            -----END PGP MESSAGE-----
          fp: 28E7C0EDF51A9283AEA43E6AC80AEE03FD22EA51
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
