apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aws-cloud-controller
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/aws-cloud-controller
  dependsOn:
    - name: auto-provider-id
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: cert-manager-cert-manager
  #     namespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
