apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/cluster-autoscaler
  dependsOn:
    - name: aws-cloud-controller
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-system-cluster-autoscaler-aws-cluster-autoscaler
      namespace: kube-system
  sourceRef:
    kind: GitRepository
    name: flux-system
