apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  force: false
  interval: 10m0s
  path: ./apps/aws-ebs-csi-driver
  prune: true
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: cert-manager-cert-manager
  #     namespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
