apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJiRENDQVJPZ0F3SUJBZ0lRVGpsaUVoKzdKRTRYeVcxdUR1NUVXREFLQmdncWhrak9QUVFEQWpBV01SUXcKRWdZRFZRUUREQXNxTG1OcGJHbDFiUzVwYnpBZUZ3MHlOVEEwTURZeE5qQTRNVFphRncweU9EQTBNRFV4TmpBNApNVFphTUJZeEZEQVNCZ05WQkFNTUN5b3VZMmxzYVhWdExtbHZNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFVUpVTDhNMS9QS3BSU3lBNnVGZklzbWhMTmdDRmt6dFd2VnJUcU5EMDljUCtVQ3ZBUktQS2kwREgKVkVld25MMkp3aytSNlBsMzdveGlpdXJQd2UyRks2TkRNRUV3RHdZRFZSMGxCQWd3QmdZRVZSMGxBREFQQmdOVgpIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRbWRUVUJ3ZzZjMk14SEZSWDhHdXBIQ3JsajFqQUtCZ2dxCmhrak9QUVFEQWdOSEFEQkVBaUFZb1RNTTZzM3BBckNCNUZCNTIvLzV0Y0VJMXd2U0NqcDFFZGNjTnV0M3dRSWcKRm1BY0IrdEV2VXFHWE9tUGVPZDJQNlJGdWNRMVo5MDVobTVaWURZNmVLdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUR2d0szT0hIY2lHcU1JWVdsTm5WTzQxWWw1REpEUisrOEVKQSs5Rzc4OVhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVUpVTDhNMS9QS3BSU3lBNnVGZklzbWhMTmdDRmt6dFd2VnJUcU5EMDljUCtVQ3ZBUktQSwppMERIVkVld25MMkp3aytSNlBsMzdveGlpdXJQd2UyRkt3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: hubble-trust-anchor
  namespace: cert-manager
type: kubernetes.io/tls
