apiVersion: v1
data:
    tls.crt: ENC[AES256_GCM,data:WBPJH2iQ0O5pz2cwzIZIKL4bcGxIWK5tpR7keyT0l3wPOdQaoIvOM1wg0N42awVA+bYa246K0iDNyZA+soQKdRSbEc6iOMXpYIboZoYGX8kd7SfCDm+ywVw8zj43Qvy9CgPyB5jirmcG+6iakHLJiMwKNCG89ZLGfILe8U9gN6WuCpsVJJt6gU7OA7AlxceFtIy+Mmoiml6pXkyA4KO04IfhZ6JnrcivMmjNOvhS6PbO5dQUNQtUHH1OEHDm6SHy1naO2Lw6OYXF71PuSltkymyz2fiyGvzT4cDnPyMZj2An7B3hQUeehoCfr8FpyiO6VfXQyVZJWpb6n0bvhZD7tkczQxfbIGq+1fT+Q1EllVBx6cnT6m5drDgh8Sayv6OU8CN0dTmjVqHn5Gd6bfLzO76WDxg0qTYBzrMoyMUZ65EyXcfpwCBkCbW3TT8UMLFLI5zF/AWP3kFEme284/+5HG5vaNuWnRbmC0v2P5KJh7+JKk+BpPiCP7DWdtFb0z0zDvzRNtHg4euCrsjRB1L8f5hZCLrHggnfduBC2ssIDtx0ygSfO7CqIL73oVAM/XSmUFDZEJMNnRAcdYfJGgCn5aoAJH/bVjdpF+huKv0e1TSYuC2lEORTV5Fl6TP0NjcMic9oLxq/Ka819tBqCqiODajnTZqeWxbV3PLLbuEVeqsGBK4vj7OWLLEbY2VKxR9iWfq0Of2mhDfvKBdWaiAkXna9i27GMTwGWEUS2qrFoPCFwxisZ2IRSHJNxqMfKASuwyzbIPzXiwEt+Wg5oU/vrejU/+nsqx+jf0kuvkBvZKroDVfKeviXvSK0cD2OVgrwyxmU1RhFag4JBWzpqzuyHU8m/x+pLX+uYidu79CVs1hK4kGa3YPT0b5JUGwp1y47Eg2ydiyCnpU0Nw3YaOaK/Ycpwu6lIe786RbhcxaSA4X41BerMQmrnoXE6IPERIarvoyyoD2e9EG6876aKxT1YfwMlU4=,iv:1MdnEr9Gnc1b9IFOgXArLZnljLyxcyTRTGQu2qu5vgg=,tag:2U4Dc5WUWRoWihQeP9Y9dg==,type:str]
    tls.key: ENC[AES256_GCM,data:mcKDjMkXL5laeP3/6+Aueb/o/FoYSrGthKYaCtx9bnZDCo5dDRaER2zjx8/gx6u8OvQ8MAFkL3jl96P1V1X9jotZDBK3LNzfl/Nc13FvSS6ROZvhtzNMNCMamKnDKH0ro+/8WNgg7gd+UOG84umZaZq1gADOj7f1Gh2T9OAoC8/OIqCDL5EaMzCx6AsGovtyo3aRQOn5lxXiE3n8kXYVDCJLH7jB79wtYBF5tF7U85S/qJgyS+sV+yAI7VT2F+usBY0T1Ac1CxDvInNBvl2d37Dk14Un9wzZN5G+nb/o4rUyDdraFPMU10vzclGjuEfwdWBTfWLXYGfhyM6gmKoGb9DC/ymPm7LDYPUlcvsV+/u8M2lqhZhlOD8mBb+YWMk9zaF4uWoGcTpbrmoHxab41g==,iv:vaW12naAMoIC3oX4LosCUDAVMW5Q7ZtC889n8C3VJ0Q=,tag:2p4OJWpx/MH/Gxzq13gx4g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: hubble-trust-anchor
    namespace: cert-manager
type: kubernetes.io/tls
sops:
    lastmodified: "2025-04-05T15:54:59Z"
    mac: ENC[AES256_GCM,data:uFdrFvufdz7zjEmDssHRQ4liiONFhWRcrTcProRt6kV0Ap+wUU3LY46/74kI27t9lQr9GLB8tNr05mjmFWwf8MVwrdYCGq/njb+W/ExZj8MruWZgER1dLXzocMXAiJPqj2noK57yCZspwxXx5EOJG8Or89ig9FDwyaDcFn1BEgQ=,iv:65Gw6HgNdemdzfKXEEax3Twdp1sO6WbmUxLSEPWGC7o=,tag:FthEGj1QPd3jqWkP+ayGkw==,type:str]
    pgp:
        - created_at: "2025-04-05T15:54:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0hiOGo6rnhLARAAplBY841Dk70EW9yK+xD3dTSkJMkl1vY6BrObnUvYvNuB
            r4I5wGV0b/+1I2FDH2m43qvYdnmk40oPAcIV3MCNZDvbCMrV0BfjQRVxPVYrVqiN
            2l++j6DNUvNof53ZYBCI+qYlz2sTwMGqwZZMR5Ou0CsENKLJq+9tedmwxTNUMnyM
            hji8S0596GxryfCSBOBkDt9ALSG6irsM4XSLLIvkqokadpF5wflRlg0SrDUrM5/k
            UrsZjaoEZam2EnNUNEckJv5UjwMdc48ayEwua/GZKABs01yojdzzJdXVR79iIbPh
            d+PFF9g/O4y2U+1pxjTPUD58SMP3jr77xJtu8Pl7LYXSnzgIGXPYvVw0tf2UJKqK
            8XjkSp7Smh8wxivRHfd6PiPcpXGlAcWn5kBta9ULIMzf5fA9z9jdeklLWbOFp8R6
            7kjzixThDWBjwgmw5ht29pH9GWivZi4iRfmvJmaqmNr/xTnuD0fRf3Tnx/D2iVME
            QRhHulUqU/SCmv+POCGD/NaMmZ7FtdJDQKYZVRQKJiFLxSTlYqO47t7B+L2S7e08
            cAGTTZMTqXDsxTpdmM7uvzvB0gHk0aVRKNOBZc+xt2ACN4wXXysuCoE3mYGgg3cW
            1I8et6H7WJvJ0n3LLgb8StlJQ9bmdSoOWNv17ajbmWCLWiaICG+HOPe6PHvKqVbS
            XgE7WbE8olmhWr33YEgr2+LaKFeNx65Ag1HPdQzAHsKqoYn5yEj7STb821VLTODc
            YqZfFqeYfYtdHRYqcFpaeqi9X7hFZicdgW07rnUdRxpQqTpdf9K+UyaRNTWb4cI=
            =XBfp
            -----END PGP MESSAGE-----
          fp: C6E05BBB4CFC79C7D9482DCDB19799B18E10ECA2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
