apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      version: 4.0.18
  releaseName: nfs-subdir-external-provisioner
  values:
    nfs:
      server: 192.168.86.2
      path: /volume1/pi-cluster
  targetNamespace: nfs-subdir-external-provisioner
  interval: 1m0s
