apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-cloud-controller-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-cloud-controller-manager
      sourceRef:
        kind: HelmRepository
        name: aws-cloud-controller-manager
      version: 0.0.8
  values:
    args:
      - --v=2
      - --cloud-provider=aws
      - --configure-cloud-routes=false
  targetNamespace: kube-system
  interval: 1m0s