apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-cloud-controller-manager
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes.github.io/cloud-provider-aws