---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dragonflydb-operator
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/dragonflydb/dragonfly-operator
  ref:
    tag: v1.1.11
