---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
  namespace: flux-system
spec:
  chart:
    spec:
      chart: zot
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: zot
      version: 0.1.75
  interval: 10m0s
  targetNamespace: zot
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/project-zot/zot
    persistence: true
    pvc:
      create: true
      storage: 50Gi
      storageClassName: local-path
    externalSecrets:
      - secretName: httpauth
        mountPath: /secret
    extraVolumes:
      - name: server-config
        configMap:
          name: server-config
    extraVolumeMounts:
      - name: server-config
        mountPath: /etc/zot
