---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zot
  namespace: flux-system
spec:
  interval: 60m0s
  provider: generic
  timeout: 10m
  url: http://zotregistry.dev/helm-charts
