apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Values.name }}
spec:
  limits:
    {{- toYaml .Values.nodePool.limits | nindent 4 }}
  disruption:
    consolidationPolicy: {{ .Values.nodePool.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.nodePool.disruption.consolidateAfter }}
    budgets:
      {{- toYaml .Values.nodePool.disruption.budgets | nindent 6 }}
  template:
    spec:
      expireAfter: {{ .Values.nodePool.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Values.name }}
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: kubernetes.io/arch
          operator: In
          values:
            {{- toYaml .Values.nodePool.architectures | nindent 12 }}
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            {{- toYaml .Values.nodePool.capacityTypes | nindent 12 }}
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            {{- toYaml .Values.nodePool.instanceCategories | nindent 12 }}
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: [{{ .Values.nodePool.minInstanceGeneration | quote }}]
