apiVersion: v1
data:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:zMbFI2qHFLSD4ZPYGA8URZfQxCZVWYWcNvZ6HhyN3WL50K7nlwdl1+WzPnIu36dgdx9q8mPwmwuI38fXirzU/m37vk6i5yXxOihfXnoJQQxnD3EzA4GSE8nu7iwn,iv:1NrgfIpYN+gL7mpzgCGwMoqnNHsMQ0zfM5xhvLoELEw=,tag:EVTUnmVO9YjbM0D0MFnGqg==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:oTKvHpQ=,iv:3zS15lpXnbXw3nlyMBlDpGEkuj6WSg6RKjyFM5560EA=,tag:7Eh1tQdWhl7cmOZXr9sQVQ==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:0xQJ+m3GDuACX5tWT7JM88797GDi8g==,iv:fewv/qr4uVcrm8kGNMBcddb+Kcwe/cy9wp3ax0huhbE=,tag:HWP71XiWtUSYCmTE9vYRog==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:oDYftpyz,iv:AaU4V/OF5t+jwASZdWILer7eg1z+cDAtZGSLFjk91os=,tag:n/Sxvz+YgWiGT6a5NyyoTw==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:OqZRUSPK3oRn6M2cSLuNA1NT1D/KmDbvJp4/952YiP0JDTxTmi28msQQ8hyHNn0GH96Jmcd1nysCSQvqasaHIYMCFhtL5dIt09bRivDcdU4xLeyEgObOeaWf0Ukd,iv:qp08KKwLMz4MbL/sL1jNccr/TE0S0T+x3TYlP1dzWgw=,tag:Lp33037BQMe14S1KXWM1LA==,type:str]
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-09T22:36:49Z"
    mac: ENC[AES256_GCM,data:xDlWNeJ+essH31Bxv+lohJbmCcyrocnjsOd+iF0iAxdXT9zg54959jEmlVUQ28bkKoIQwPp0g4itn0GNofxbps6wAsEy9tE7Dohn5jl2Wgv6F1Vg9uV98daySfookzFKK+O7MRsyRPSMcgPE1+T99UNAgcoScMiXmwVTiSp8RGU=,iv:CTxN3Um64cSEWihsg+IXxEQ3dGBy4bLc2cWLq6Nt7cw=,tag:LFfWlmMnWdRDkfHyQ2I2Rg==,type:str]
    pgp:
        - created_at: "2024-06-09T22:36:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3RMxBeN8HBhAQ//QSGLZQ5cDBwC2aUcZakpfbPK0xmoxtcIPh6cCiWre/wK
            VQqGtWxTBsUGJfqmKvrfPjcGRKQmW+OKOj3BY1uwDCSbaPNFgEQZIzDorbe5uBeg
            4EOGIfyOJL+SGIJZ2tO+RHhtR0JVJRO4qCin9/7Yhca9+cDsou08RZHTJRTk5ogD
            pIsXxVLWCm9Juu/uAkP4+EMAW6U1ODUDCe8lWxaa62tBK/P0IMxBnR2i1M8jGhWH
            MtZZFgGLjXvIZqKDg7ud82H/Vwr3T5a+u3CU52loVbVCj9CNKAapDFb32q6TJ6Sr
            OIz2ZVba+iN9o4WSpA2RrivrTVJRFXB55EtENiztPph1VGfEe/4bH9NqpUDUEJLR
            2SpfNSznA97YQGslOptGi3hUCNac2Y+YucjtLFoHz6xZmJ0UXI1eJcCSXPbAJw2Y
            AhctydNx1AaXoYVliHmQYB+6DowTzlKM8XSWiZ2J0EZzg+wyuIMADIcRZ4RDWK2D
            EbaAhk4O1/Lttl3qJYijeWT0uMmmbtFU7EwUQtOnF/5LE0aeQmwAAIhAeHEVQNPA
            ZOscSaS0iKmOADH/gqX14Hv823uF/sk3Ox20UW6nJCD/TQ50i+T6NxfSHj/nzgN1
            VUaQeVMRNe744KmQq1Ll2rGLMON1/xqZtJVTGZsoB6O1Sy8PwBOy0QGYtL5reg/U
            aAEJAhA9Z2un/0se3rFP7ZcYC1PoNpkEMPoOwj1sBwxggtTif5+m04yI5nViTXaa
            QjmlpHUBOToIbujkJhA6glgK7hWhuYoMr3LHostUmC8WrV9IBAWdvA8rnWp1HWPk
            VKYT6SKZ+/VA
            =oDk0
            -----END PGP MESSAGE-----
          fp: 37789BA069FF4ED2CC9090EEA05A04C2254C3CF1
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
