---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-flux-bootstrap
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:37.172.2
              args:
                - "pfenerty/flux-bootstrap"
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-auto-provider-id
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:37.172.2
              args:
                - "pfenerty/auto-provider-id"
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never
