apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-namepsace
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/cnpg/namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-workload
  namespace: cnpg-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/cnpg/workload
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cnpg-system-cnpg-operator-cloudnative-pg
      namespace: cnpg-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
