apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio-operator-namepsace
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/minio-operator/namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio-operator-workload
  namespace: minio-operator
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/minio-operator/workload
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: minio-operator
      namespace: minio-operator
    - apiVersion: apps/v1
      kind: Deployment
      name: console
      namespace: minio-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
