---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/vault
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vault-vault-agent-injector
      namespace: vault
    - apiVersion: apps/v1
      kind: Deployment
      name: vault-vault-vso-vault-secrets-operator-controller-manager
      namespace: vault
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault-vault
      namespace: vault
  sourceRef:
    kind: GitRepository
    name: flux-system
