apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-crds
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/monitoring/crds
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
  sourceRef:
    kind: GitRepository
    name: flux-system
