apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/monitoring/stack
  dependsOn:
    - name: aws-ebs-csi-driver
    # - name: logging
    - name: monitoring-namespace
    - name: monitoring-crds
    - name: prometheus-community-repo
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: monitoring-kube-prometheus-stack-prometheus-node-exporter
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: monitoring-kube-prometheus-operator
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: monitoring-kube-prometheus-stack-grafana
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: monitoring-kube-prometheus-stack-kube-state-metrics
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus-monitoring-kube-prometheus-prometheus
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: alertmanager-monitoring-kube-prometheus-alertmanager
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
