apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:85+CgDW+vFq5XaG8fq8/rlSm4Sh8hXt/povJll4i/88bZuuk9XUptUScXVP5e0PPduCKWQdHtaSFF+AfG2GX20J6a1uX6Rb8OQ7OHw9nlprTm7Xk9tzzXp2KJEXD,iv:IMj/UUblPFZeQv0xHNxZgTh0ZKqmAPQ6MNa1gQuxiKI=,tag:1qt5gv1JzGUm1qb24fu2pg==,type:str]
    #ENC[AES256_GCM,data:6nKXg6ikRwUC3VafcyK7++C8mvwuc262GNgnibD7fomMbiKYcpjRgS2dntWx29cL0Pp3XGiEhGEO4awnWX9nVlaMnySepC4FRheELWdMkkI63mPtBNZbf2YUmwoGhyI=,iv:K2bW8aB0bOi3pkNhQPdvLNaeAmLY9WYPw+ttq5tlLiQ=,tag:30JtnY0T85/Sn58jI8t4BQ==,type:comment]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:FMKUhO0=,iv:/zxsSpN1sEfXBSg4XPxJ5DCa04ReZDhrG6ZNoDobBKY=,tag:pbk4gpWAd6ILqR8A8VRzEQ==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:DsnlHOaSfjVmW1j2fNUoHkYyeWc+7R1Xq59LknW0KcXj,iv:kQJhpxxBvlhd2ET0wQrVu8fQnKpuvpNBnh0+SGrzmu4=,tag:Q4dEY6k9M8sNDCCmkJj1PQ==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:pDdNJJoXDv3voMhzyXZlDY/IpimP91q1wsZ8QDkDEqwmWQ==,iv:X2ccZA4i+Z3vhA9Jc1iV+aEnWpbrUfpgzS+sTZSWL1Q=,tag:7ejSWPagqJO0PYT+DLgF3g==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:ttxCSjwD,iv:Lfkfuf7HY7ShlAhFLnxYSAxVLbglv4TVXLGI2Sb3z8g=,tag:HnZumXxXxf/XIieOVRrgNg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:XMn7yr99YD93/yxtB2grRepyKAFbBFI7Jbxcu6Td2VbPesLvn4EXBWkaL+F3h/emsSfsAoUie32wM+w7ENG7XmMOJFicfpIO1IxcsECEg/woWdWgVZ/iPAn/m+2Q,iv:8l3Dl4OIeUJqYB2y6ke9wkGxjN2gBKUB23fEPA+F2uU=,tag:gPaoIlu2DKZpM3jmbo3+NQ==,type:str]
sops:
    lastmodified: "2025-04-06T16:54:11Z"
    mac: ENC[AES256_GCM,data:A2jsMBUJEDUcZV5wxx9gEbF/ich58HXziNO4JFaNvrFfZG930Ql8n7BDxN5q0Yea7RxHGR8I+x4YinA/w9orxxn0F4JMssoxTudhai2WIt3M3ZsWyMSecYioqnqiMgG8SOqeBYXcYZw9LCnJz1/wfDLiAaP5u8UjcO7qeEV8Iuw=,iv:8e55rKNgXVqc8B76wgJh0mLbddUxq4LG1t0cBNx8TY8=,tag:A6EQPe1N464zVy0fOy+B6w==,type:str]
    pgp:
        - created_at: "2025-04-06T16:54:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0hiOGo6rnhLAQ/+LFhJsWzwJeNMwf/f1AJ+ahsVnhuhkOcgPedesAlOKDyw
            WRVCkQfalKES+d0/EbfqJvGGE5sF8f/Lv+Aj/ioLxKnq4FI8Al2UYqqwt9LndkXM
            HIlxnw2zsHr7D+xnC1xz7d7W7AdLJzENwWixHP+lcxZpRvXZZ1t19XV9Olv2mFIV
            yj1Hw+yonLQh3LoRvqZPguFz/OszjdH7iRtE2YFpSH6+LqcZTL3sqmPpbdOCWxCa
            8+3ETctPkvuKlPKapdX0jTgmaLVopTRwiSQsZ49LYnk+SMPdL2WzlE/y8VLFOXUU
            c58mJuXixfeQ4H8Ud98MwhVl1M0rNYsK1ScPPo+Crs6XvjG/i5Afhqs8a7aDSw7M
            W8b5dZlfPeIhgdRj7iCGKleko69laytdV0vawWGyR7EfMZ3pWrtqc6VDm57si+fb
            5XV+mp6trKQLr7HMtIwHIuTYOUpqRnEH7iBKoesZUAuWp88qEDXLArA49D28ijJd
            o7PaX233reg7VG5IxTC6qvES0AyjGQ2ZH99wFRmlAtg0J0JAhcDLtsPYGHLEoFBx
            YD9fx1wbVc9GmcsQ1sPsFmH10AX7WQf7Z2VJjZEuhJ15N3G4TReF6CuWpipSV8wB
            G3WO+O2KHzgOvaiglnXBCMo/f8HtuIHsRaivTwUjDRrapD2aTMPCQ+sZsJcMFarS
            XgFxbpBEo8gfyWnjhrUgArCtlANH4RSrvZ1EJVGSsPH+qJfUwtyKUtYO+TJkb6iD
            npGQPZAs2KJGdEgg36tK5ghHA3IYOBwOd/TWufDCb/HodKPFJHO86NHTN+8ptXg=
            =Xqme
            -----END PGP MESSAGE-----
          fp: C6E05BBB4CFC79C7D9482DCDB19799B18E10ECA2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
