apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 70.7.0
  releaseName: kube-prometheus-stack
  values:
    # prometheusOperator:
    #   namespaces:
    #     additional:
    #       - kube-system
    cleanPrometheusOperatorObjectNames: true
    fullnameOverride: kps
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        securityContext:
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
          fsGroup: 2000
          seccompProfile:
            type: RuntimeDefault
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
    grafana:
      additionalDataSources:
        - name: Loki
          access: proxy
          basicAuth: false
          basicAuthPassword: ""
          basicAuthUser: ""
          editable: false
          jsonData: {}
          orgId: 1
          type: loki
          url: http://logging-loki-stack-headless.logging.svc.cluster.local:3100
          version: 1
  targetNamespace: monitoring
  install:
    crds: Skip
  interval: 1m0s
