apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.9.10
  values:
    loki:
      minio:
        enabled: true
    promtail:
      serviceMonitor:
        enabled: true
  targetNamespace: logging
  interval: 1m0s