apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.9.10
  values:
  # loki:
  #   storage_config:
  #     aws:
  #       s3: s3://access_key:secret_access_key@region/bucket_name
  #       dynamodb:
  #         dynamodb_url: dynamodb://access_key:secret_access_key@region
  #   promtail:
  #     serviceMonitor:
  #       enabled: true
  valuesFrom:
    - kind: Secret
      name: loki-storage-config
      valuesKey: bucket_name
      targetPath: loki.storage.s3.s3
    - kind: Secret
      name: loki-storage-config
      valuesKey: key_id
      targetPath: loki.storage.s3.accessKeyId
    - kind: Secret
      name: loki-storage-config
      valuesKey: access_key
      targetPath: loki.storage.s3.secretAccessKey
    - kind: Secret
      name: loki-storage-config
      valuesKey: region
      targetPath: loki.storage.s3.region
    - kind: Secret
      name: loki-storage-config
      valuesKey: dynamodb_url
      targetPath: loki.storage_config.aws.dynamodb.dynamodb_url
    - kind: Secret
      name: loki-storage-config
      valuesKey: s3_url
      targetPath: loki.storage_config.aws.s3
  targetNamespace: logging
  interval: 1m0s