apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.9.11
  # values:
  #   loki:
  #     config:
  #       schema_config:
  #         configs:
  #         - from: "2020-05-15"
  #           store: aws
  #           object_store: s3
  #           schema: v11
  #           index:
  #             prefix: loki_
  #       # storage_config:
  #       #   aws:
  #       #     s3: "s3://access_key:secret_access_key@region/bucket_name"
  #       #     dynamodb:
  #       #       dynamodb_url: "dynamodb://access_key:secret_access_key@region"
  # valuesFrom:
  #   - kind: Secret
  #     name: loki-storage-config
  #     valuesKey: dynamodb_url
  #     targetPath: loki.config.storage_config.aws.dynamodb.dynamodb_url
  #   - kind: Secret
  #     name: loki-storage-config
  #     valuesKey: s3_url
  #     targetPath: loki.config.storage_config.aws.s3
  targetNamespace: logging
  interval: 1m0s