apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-labeler
  namespace: kube-system
  labels:
    app: k8s-node-labeler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-node-labeler
  template:
    metadata:
      labels:
        app: k8s-node-labeler
    spec:
      serviceAccountName: node-watcher
      containers:
      - name: node-labeler
        image: pfenerty/k8s-node-labeler:latest
        command: ["/app"]
        args: ["operator"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      tolerations:
      - key: "node.cloudprovider.kubernetes.io/uninitialized"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"