apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-provider-id
  namespace: auto-provider-id
  labels:
    app: auto-provider-id
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-provider-id
  template:
    metadata:
      labels:
        app: auto-provider-id
    spec:
      serviceAccountName: node-watcher
      containers:
      - name: operator
        image: pfenerty/auto-provider-id:v0.0.1
        command: ["/ko-app/auto-provider-id"]
        args: ["operator"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      tolerations:
      - key: "node.cloudprovider.kubernetes.io/uninitialized"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"