apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-watcher
  namespace: auto-provider-id
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-updater
  namespace: auto-provider-id
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-watcher
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-updater
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-watcher-binding
subjects:
- kind: ServiceAccount
  name: node-watcher
  namespace: auto-provider-id
roleRef:
  kind: ClusterRole
  name: node-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-updater-binding
subjects:
- kind: ServiceAccount
  name: node-updater
  namespace: auto-provider-id
roleRef:
  kind: ClusterRole
  name: node-updater
  apiGroup: rbac.authorization.k8s.io
