---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 60m0s
  provider: generic
  timeout: 60s
  url: https://helm.releases.hashicorp.com