---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-vso
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault-secrets-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      version: 0.9.1
  interval: 10m0s
  targetNamespace: vault
  values:
    controller:
      manager:
        clientCache:
          persistenceModel: direct-encrypted
          storageEncryption:
            enabled: true
            keyName: vso-client-cache
            kubernetes:
              role: auth-role-operator
              serviceAccount: vso
            mount: vso-auth-mount
            transitMount: vso-transit
    defaultVaultConnection:
      address: http://vault-vault.vault.svc.cluster.local:8200
      enabled: true
      skipTLSVerify: false
