apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-secrets
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./secrets/pi-cluster/tekton
  decryptionProvider: sops
  decryptionSecret: sops-gpg
  sourceRef:
    kind: GitRepository
    name: flux-system
