apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-workloads
  namespace: flux-system
spec:
  force: false
  interval: 3m0s
  retryInterval: 60s
  prune: true
  path: ./apps/tekton/workloads
  dependsOn:
    - name: tekton-namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-events-controller
      namespace: tekton-pipelines
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-pipelines-controller
      namespace: tekton-pipelines
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-pipelines-webhook
      namespace: tekton-pipelines
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-tiggers-controller
      namespace: tekton-pipelines
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-triggers-core-interceptors
      namespace: tekton-pipelines
    - apiVersion: apps/v1
      kind: Deployment
      name: tekton-triggers-webhook
      namespace: tekton-pipelines