apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-ebs-csi-driver
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
      version: 2.27.0
  values:
    storageClasses:
      - name: ebs-sc
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        volumeBindingMode: WaitForFirstConsumer
        reclaimPolicy: Delete
        parameters:
          encrypted: "false"
  targetNamespace: kube-system
  interval: 1m0s