apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
      version: 10.6.0
  values:
    global:
      storageClass: local-path
    gitea:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      config:
        server:
          ENABLE_PPROF: true
        database:
          DB_TYPE: postgres
    redis-cluster:
      enabled: true
    postgresql-ha:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: db-cluster-app
      valuesKey: host
      targetPath: gitea.config.database.HOST
    - kind: Secret
      name: db-cluster-app
      valuesKey: user
      targetPath: gitea.config.database.USER
    - kind: Secret
      name: db-cluster-app
      valuesKey: password
      targetPath: gitea.config.database.PASSWD
    - kind: Secret
      name: db-cluster-app
      valuesKey: dbname
      targetPath: gitea.config.database.NAME
  targetNamespace: gitea
  install:
    createNamespace: true
    crds: CreateReplace
  interval: 1m0s
